### ISSUE TITLE
Possible issue with v28.0.0

### ISSUE THREAD

**Issue by ryanlelek** [google/google-api-nodejs-client#1094]
@JustinBeckwith - Encountered issue when upgrading to v28.0.0 through NPM.
Thought it might be because I'm not using TypeScript, but even so, it still may break builds.
Using v27.0.0 restored successfully so it seems the issue is isolated to v28.0.0.
Reporting early in hopes if this is a true issue, impact is reduced

Example...
- Start with an empty directory (preferably outside a parent path with `node_modules/`)
- `npm install googleapis`
- new `index.js` file
```
'use strict';
var google = require('googleapis');
```

- Run the script
```
$ node index.js 
module.js:549
    throw err;
    ^

Error: Cannot find module 'googleapis'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
```

Let me know if there's something else I can do to diagnose.
Ryan

Node: v8.10.0
NPM: v5.8.0

**Comment by JustinBeckwith** [comment]
Confirmed.  I'm actively working on a fix.  Apologies folks!

**Comment by JustinBeckwith** [comment]
Thanks for the patience! I think we have this worked out in 28.0.1.  PTAL!

**Comment by ryanlelek** [comment]
Confirmed Fixed. Thanks

**Comment by Coriou** [comment]
Hey. Exact same problem with `31.0.0` and node `9.4.0`

What I did :


`$ npm i googleapis`
`const {google} = require('googleapis')`

Getting : `Cannot find module 'googleapis'`
