### ISSUE TITLE
`purchases.products` or `inappproducts` does not exist on google.androidpublisher('v2')

### ISSUE THREAD

**Issue by sqmk** [google/google-api-nodejs-client#1112]
Attempting to upgrade from 27.0.0 to 28.1.0 results in issues attempting to access `purchases.products` and `inappproducts` properties on google.androidpublisher('v2'). I'd imagine other properties aren't accessible.

Note: The following pseudocode would work in 27.0.0, but not in 28.1.0, where type definitions were introduced. Currently running in a typescript 2.8.1 env.

```
const androidPublisherClient = google.androidpublisher('v2')

androidPublisherClient.purchases.products.get({
  packageName: 'sample',
  productId: 'sample',
  token: 'sample',
  auth: oauth2client
}, null, function(err: any, response: any) {
 // Sample
})
```

Sample errors returned:

```
error TS2339: Property 'products' does not exist on type 'Resource$Purchases | Resource$Purchases | Resource$Purchases'.
  Property 'products' does not exist on type 'Resource$Purchases'
```
```
Property 'inappproducts' does not exist on type 'Androidpublisher | Androidpublisher | Androidpublisher'.
  Property 'inappproducts' does not exist on type 'Androidpublisher'.
```
